### ISSUE TITLE
[BUG]PHP Fatal error:  Uncaught Error: Class "ZipArchive" not found in /var/www/plugins.local/data_migration/init.php:46

### ISSUE THREAD

**Issue by ccinoo** [HenryQW/Awesome-TTRSS#307]
**Bug 描述**
您好，我是从源库v20.12-d4666d3（非容器MySQL）迁移数据至新库v21.05-295fc1f（Awesome-TTRSS容器）环境。需求是迁移含源库中“标星“条目，研究后使用data_migration插件。源库导出正常，新库导入是出现如下报错。

/var/www # sudo -u nginx php ./update.php --data_user admin --data_import articles-of-user-admin.zip
[10:50:20/10661] Lock: update.lock
[10:50:20/10661] importing articles of user admin from articles-of-user-admin.zip...
PHP Fatal error:  Uncaught Error: Class "ZipArchive" not found in /var/www/plugins.local/data_migration/init.php:46
Stack trace:
#0 /var/www/classes/pluginhost.php(420): Data_Migration->data_import()
#1 /var/www/update.php(395): PluginHost->run_commands()
#2 {main}
  thrown in /var/www/plugins.local/data_migration/init.php on line 46

**你谷歌/百度了吗？**

搜索到非容器环境安装php zip模块，找不到容器环境如何安装php zip模块

**部署方法**
 - Docker 或 docker-compose
 - 使用的镜像版本 [如 latest, nightly, 19.8]
使用Awesome-TTRSS  docker-compose

**部署环境**
CentOS Linux release 7.9.2009 (Core)

[root@centos7 ~]# docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED        STATUS        PORTS                                 NAMES
56f24cab65f8   wangqiru/mercury-parser-api:latest   "dumb-init -- npm ru…"   47 hours ago   Up 47 hours   3000/tcp                              mercury
e9060167a04c   wangqiru/ttrss:latest                "sh /docker-entrypoi…"   47 hours ago   Up 47 hours   0.0.0.0:181->80/tcp, :::181->80/tcp   ttrss
e17b6224ab5e   postgres:13-alpine                   "docker-entrypoint.s…"   47 hours ago   Up 47 hours                                         postgres
cca3b1bd5a0d   wangqiru/opencc-api-server:latest    "docker-entrypoint.s…"   47 hours ago   Up 47 hours                                         opencc
cca4d5626963   containrrr/watchtower:latest         "/watchtower"            47 hours ago   Up 47 hours   8080/tcp                              watchtower

**复现步骤**
复现该 bug 的详细步骤
1. 打开 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 发现错误

**预期结果**
简洁明了地描述正确的预期结果该是怎样的。

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

[root@centos7 ~]# docker logs ttrss --tail 100
[11:03:00/11371] Lock: update_daemon-feed-78.lock
[11:03:04/11340] <= 4.0697 (sec) exit code: 0
[11:03:04/11340] Base feed: https://rss.now.sh/twitter/user/taylorswift13
[11:03:04/11340] => Taylor Swift 的 Twitter (ID: 86, U: admin [1]), last updated: 2021-06-16 10:46:57
[11:03:04/11376] Lock: update_daemon-feed-86.lock
[11:03:05/11340] <= 1.1803 (sec) exit code: 0
[11:03:05/11340] Base feed: http://wpchina.org/feed/
[11:03:05/11340] => WordPress中文网 (ID: 51, U: admin [1]), last updated: 2021-06-16 10:46:58
[11:03:05/11380] Lock: update_daemon-feed-51.lock
[11:03:06/11340] <= 1.0379 (sec) exit code: 0
[11:03:06/11340] Base feed: https://www.xqblog.com/feed
[11:03:06/11340] => VPS推荐网 (ID: 46, U: admin [1]), last updated: 2021-06-16 10:46:59
[11:03:06/11383] Lock: update_daemon-feed-46.lock
[11:03:06/11340] <= 0.7662 (sec) exit code: 0
[11:03:06/11340] Base feed: http://www.138vps.com/rss.php
[11:03:06/11340] => 分享便宜的美国vps (ID: 58, U: admin [1]), last updated: 2021-06-16 10:47:02
[11:03:07/11386] Lock: update_daemon-feed-58.lock
[11:03:09/11340] <= 2.4935 (sec) exit code: 0
[11:03:09/11340] Base feed: https://kuriko.org/index.php/announcements/rss
[11:03:09/11340] => Kuriko (ID: 22, U: admin [1]), last updated: 2021-06-16 10:47:06
[11:03:09/11391] Lock: update_daemon-feed-22.lock
[11:03:13/11340] <= 3.6133 (sec) exit code: 0
[11:03:13/11340] Base feed: https://aimingoo.github.io/rss/
[11:03:13/11340] => Aimingoo's Blog (ID: 96, U: admin [1]), last updated: 2021-06-16 10:47:07
[11:03:13/11396] Lock: update_daemon-feed-96.lock
[11:03:14/11340] <= 1.8282 (sec) exit code: 0
[11:03:14/11340] Base feed: https://www.nginx.com/feed/
[11:03:14/11340] => NGINX (ID: 29, U: admin [1]), last updated: 2021-06-16 10:47:08
[11:03:15/11399] Lock: update_daemon-feed-29.lock
[11:03:15/11340] <= 0.8832 (sec) exit code: 0
[11:03:15/11340] Base feed: https://linux.cn/rss.xml
[11:03:15/11340] => Linux中国开源社区 (ID: 176, U: admin [1]), last updated: 2021-06-16 10:47:11
[11:03:16/11402] Lock: update_daemon-feed-176.lock
[11:03:18/11340] <= 2.4391 (sec) exit code: 0
[11:03:18/11340] Base feed: https://websound.co.uk/announcementsrss.php
[11:03:18/11340] => WebSound (ID: 50, U: admin [1]), last updated: 2021-06-16 10:47:17
[11:03:18/11407] Lock: update_daemon-feed-50.lock
[11:03:22/11340] <= 4.7085 (sec) exit code: 0
[11:03:22/11340] Base feed: https://manage.hostdare.com/announcements/rss
[11:03:22/11340] => HostDare (ID: 20, U: admin [1]), last updated: 2021-06-16 10:47:21
[11:03:23/11412] Lock: update_daemon-feed-20.lock
[11:03:26/11340] <= 3.5100 (sec) exit code: 0
[11:03:26/11340] Base feed: http://feeds.feedburner.com/ruanyifeng
[11:03:26/11340] => 阮一峰的网络日志 (ID: 147, U: admin [1]), last updated: 2021-06-16 10:47:22
[11:03:27/11417] Lock: update_daemon-feed-147.lock
[11:03:27/11340] <= 1.4811 (sec) exit code: 0
[11:03:27/11340] Processed 18 feeds in 44.9676 (sec), 2.4982 (sec/feed avg)
[11:03:27/11340] Running housekeeping tasks for user 1...
[11:03:28/11340] Sending digests, batch of max 15 users, headline limit = 1000
[11:03:28/11340] All done.
[11:03:28/11340] Expired cache/export: removed 0 files.
[11:03:28/11340] Expired cache/feeds: removed 0 files.
[11:03:28/11340] Expired cache/images: removed 0 files.
[11:03:28/11340] Expired cache/upload: removed 0 files.
[11:03:28/11340] Removed 0 old lock files.
[11:03:28/11340] Removing old error log entries...
[11:03:28/11340] Purged 0 orphaned posts.
[11:03:29/29] Child process with PID 11338 reaped.
[11:03:29/29] Received SIGCHLD, 0 active tasks left.
[11:03:42/29] 0 active tasks, next spawn at 60 sec.
[11:04:42/29] 0 active tasks, next spawn at 0 sec.
[11:04:43/29] Spawned child process with PID 11428 for task 0.
[11:04:43/29] Spawned child process with PID 11429 for task 1.
[11:04:48/11430] Using task id 1
[11:04:48/11430] Lock: update_daemon-11429.lock
[11:04:48/11430] Waiting before update (5)...
[11:04:48/11431] Using task id 0
[11:04:48/11431] Lock: update_daemon-11428.lock
[11:04:48/11431] Waiting before update (0)...
[11:04:49/11431] Scheduled 15 feeds to update...
[11:04:49/11431] Base feed: https://cn.engadget.com/rss.xml
[11:04:49/11431] => Engadget 中文版 RSS Feed (ID: 153, U: admin [1]), last updated: 2021-06-16 10:49:11
[11:04:49/11434] Lock: update_daemon-feed-153.lock
[11:04:53/11430] Scheduled 1 feeds to update...
[11:04:53/11430] Base feed: https://hostodo.com/portal/index.php?rp=/announcements/rss
[11:04:53/11430] => Hostodo (ID: 21, U: admin [1]), last updated: 2021-06-16 10:49:53
[11:04:55/11439] Lock: update_daemon-feed-21.lock
[11:04:57/11431] <= 8.3717 (sec) exit code: 0
[11:04:57/11431] Base feed: https://rsshub.app/mafengwo/note/hot
[11:04:57/11431] => 马蜂窝游记 (ID: 94, U: admin [1]), last updated: 2021-06-16 10:49:13
[11:04:57/11444] Lock: update_daemon-feed-94.lock
[11:04:58/11431] <= 1.0354 (sec) exit code: 0
[11:04:58/11431] Base feed: https://www.moerats.com/feed
[11:04:58/11431] => Rat's Blog (ID: 34, U: admin [1]), last updated: 2021-06-16 10:49:16
[11:04:58/11447] Lock: update_daemon-feed-34.lock
[11:05:02/11431] <= 3.6517 (sec) exit code: 0
[11:05:02/11431] Base feed: http://www.geekpark.net/rss
[11:05:02/11431] => 极客公园 (ID: 195, U: admin [1]), last updated: 2021-06-16 10:49:18
[11:05:02/11430] <= 8.4614 (sec) exit code: 0
[11:05:02/11430] Processed 1 feeds in 8.4653 (sec), 8.4653 (sec/feed avg)
[11:05:02/11430] Running housekeeping tasks for user 1...
[11:05:02/11455] Lock: update_daemon-feed-195.lock
[11:05:02/11430] Sending digests, batch of max 15 users, headline limit = 1000
[11:05:02/11430] All done.
[11:05:04/11431] <= 2.7239 (sec) exit code: 0
[11:05:04/11431] Base feed: http://tt-rss.org/forum/rss.php
[11:05:04/11431] => Tiny Tiny RSS: Forum (ID: 202, U: admin [1]), last updated: 2021-06-16 10:49:27
[11:05:05/11458] Lock: update_daemon-feed-202.lock
[11:05:05/29] Child process with PID 11429 reaped.
[11:05:05/29] Received SIGCHLD, 1 active tasks left.

**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
docker exec -it 目标容器 sh 
安装相关php extension

**Comment by ccinoo** [comment]
感谢最新容器镜像中这么快增加了zip模块。可惜我的两个TTRS版本schema不同，最终使用data_migration插件迁移星标文章（1500多篇）没有成功。

如果您这能提供些其他建议的话，非常感谢。目前报错如下：

[22:35:51]/var/www # sudo -u nginx php ./update.php --data_user abc --data_import articles-of-user-abc.zip
[22:35:51][14:33:32/714] Lock: update.lock
[22:35:51][14:33:32/714] importing articles of user admin from articles-of-user-admin.zip...
[22:35:51][14:33:32/714] processing 00000000.json
[22:35:52][14:33:32/714] batch has incorrect schema format version (expected: 145, got: 140
[22:35:52][14:33:32/714] processing 00000001.json
[22:35:52][14:33:33/714] batch has incorrect schema format version (expected: 145, got: 140
.
.
.
[22:36:14][14:33:55/714] processing 00000095.json
[22:36:15][14:33:55/714] batch has incorrect schema format version (expected: 145, got: 140
[22:36:15][14:33:55/714] processing 00000096.json
[22:36:15][14:33:55/714] batch has incorrect schema format version (expected: 145, got: 140
[22:36:15][14:33:55/714] imported 0 (out of 0) articles, created 0 feeds.

**Comment by HenryQW** [comment]
ttrss数据库版本不对，导出的是145，导入目标数据库版本是140
用最新的景象，更新一下schema
