### ISSUE TITLE
[BUG]rss-hub源无法订阅

### ISSUE THREAD

**Issue by HawkQ** [HenryQW/Awesome-TTRSS#346]
**Bug 描述**
通过docker-compose部署后所有添加的源均被列为feeds with errors
同时无法使用fever插件

**你谷歌/百度了吗？**
有类似日志的问题但是完全不通用

**部署方法**
 - docker-compose
 - latest

**部署环境**
 - debian 10
 - 浏览器：Edge for macOS

**复现步骤**
复现该 bug 的详细步骤
1. 添加‘订阅源’
2. 显示‘Feeds with errors’

**预期结果**
应当正确添加源

**截屏**
尚无

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。
[04:18:18/165] Base feed: （此处是我的源，确认过其他手段订阅可用）
[04:18:18/165] => [Unknown] (ID: 3, U: admin [1]), last updated: never
[04:18:18/178] Lock: update_daemon-feed-3.lock
[04:18:18/178] setting basic feed info for 3...
PHP Fatal error:  Uncaught ValueError: DOMDocument::loadXML(): Argument #1 ($source) must not be empty in /var/www/classes/feedparser.php:36
Stack trace:
#0 /var/www/classes/feedparser.php(36): DOMDocument->loadXML()
#1 /var/www/classes/rssutils.php(310): FeedParser->__construct()
#2 /var/www/classes/rssutils.php(385): RSSUtils::update_basic_info()
#3 /var/www/update.php(232): RSSUtils::update_rss_feed()
#4 {main}
  thrown in /var/www/classes/feedparser.php on line 36
[04:18:18/165] <= 0.0854 (sec) exit code: 255
[04:18:18/165] !! Last error: Update process failed with exit code: 255 ()
[04:18:18/165] Base feed: （此处是我的源，确认过其他手段订阅可用）
[04:18:18/165] => [Unknown] (ID: 8, U: admin [1]), last updated: never
[04:18:18/180] Lock: update_daemon-feed-8.lock
[04:18:18/180] setting basic feed info for 8...
PHP Fatal error:  Uncaught ValueError: DOMDocument::loadXML(): Argument #1 ($source) must not be empty in /var/www/classes/feedparser.php:36
Stack trace:
#0 /var/www/classes/feedparser.php(36): DOMDocument->loadXML()
#1 /var/www/classes/rssutils.php(310): FeedParser->__construct()
#2 /var/www/classes/rssutils.php(385): RSSUtils::update_basic_info()
#3 /var/www/update.php(232): RSSUtils::update_rss_feed()
#4 {main}
  thrown in /var/www/classes/feedparser.php on line 36
[04:18:18/165] <= 0.0850 (sec) exit code: 255
[04:18:18/165] !! Last error: Update process failed with exit code: 255 ()
[04:18:18/165] Processed 7 feeds in 0.6594 (sec), 0.0942 (sec/feed avg)
[04:18:18/165] Running housekeeping tasks for user 1...
[04:18:18/165] Sending digests, batch of max 15 users, headline limit = 1000
[04:18:18/165] All done.
[04:18:18/165] Expired cache/export: removed 0 files.
[04:18:18/165] Expired cache/feeds: removed 0 files.
[04:18:18/165] Expired cache/images: removed 0 files.
[04:18:18/165] Expired cache/upload: removed 0 files.
[04:18:18/165] Removed 0 old lock files.
[04:18:18/165] Removing old error log entries...
[04:18:18/165] Purged 0 orphaned posts.
[04:18:19/31] Child process with PID 162 reaped.
[04:18:19/31] Received SIGCHLD, 1 active tasks left.
[04:18:22/164] Scheduled 0 feeds to update...
[04:18:22/164] Sending digests, batch of max 15 users, headline limit = 1000
[04:18:22/164] All done.
[04:18:23/31] Child process with PID 163 reaped.
[04:18:23/31] Received SIGCHLD, 0 active tasks left.
[04:19:17/31] 0 active tasks, next spawn at 60 sec.
[04:20:17/31] 0 active tasks, next spawn at 0 sec.
[04:20:18/31] Spawned child process with PID 189 for task 0.
[04:20:18/31] Spawned child process with PID 190 for task 1.
[04:20:19/191] Using task id 1
[04:20:19/192] Using task id 0
[04:20:19/192] Lock: update_daemon-189.lock
[04:20:19/192] Waiting before update (0)...
[04:20:19/191] Lock: update_daemon-190.lock
[04:20:19/191] Waiting before update (5)...
[04:20:19/192] Scheduled 0 feeds to update...
[04:20:19/192] Sending digests, batch of max 15 users, headline limit = 1000
[04:20:19/192] All done.
[04:20:19/192] Expired cache/export: removed 0 files.
[04:20:19/192] Expired cache/feeds: removed 0 files.
[04:20:19/192] Expired cache/images: removed 0 files.
[04:20:19/192] Expired cache/upload: removed 0 files.
[04:20:19/192] Removed 0 old lock files.
[04:20:19/192] Removing old error log entries...
[04:20:19/192] Purged 0 orphaned posts.
[04:20:20/31] Child process with PID 189 reaped.
[04:20:20/31] Received SIGCHLD, 1 active tasks left.
[04:20:24/191] Scheduled 0 feeds to update...
[04:20:24/191] Sending digests, batch of max 15 users, headline limit = 1000
[04:20:24/191] All done.
[04:20:25/31] Child process with PID 190 reaped.
[04:20:25/31] Received SIGCHLD, 0 active tasks left.
[04:21:18/31] 0 active tasks, next spawn at 60 sec.
[04:22:18/31] 0 active tasks, next spawn at 0 sec.
[04:22:19/31] Spawned child process with PID 197 for task 0.
[04:22:19/31] Spawned child process with PID 198 for task 1.
[04:22:19/200] Using task id 0
[04:22:19/199] Using task id 1
[04:22:19/200] Lock: update_daemon-197.lock
[04:22:19/199] Lock: update_daemon-198.lock
[04:22:19/200] Waiting before update (0)...
[04:22:19/199] Waiting before update (5)...
[04:22:19/200] Scheduled 0 feeds to update...
[04:22:19/200] Sending digests, batch of max 15 users, headline limit = 1000
[04:22:19/200] All done.
[04:22:19/200] Expired cache/export: removed 0 files.
[04:22:19/200] Expired cache/feeds: removed 0 files.
[04:22:19/200] Expired cache/images: removed 0 files.
[04:22:19/200] Expired cache/upload: removed 0 files.
[04:22:19/200] Removed 0 old lock files.
[04:22:19/200] Removing old error log entries...
[04:22:19/200] Purged 0 orphaned posts.
[04:22:20/31] Child process with PID 197 reaped.
[04:22:20/31] Received SIGCHLD, 1 active tasks left.
[04:22:24/199] Scheduled 0 feeds to update...
[04:22:24/199] Sending digests, batch of max 15 users, headline limit = 1000
[04:22:24/199] All done.
[04:22:25/31] Child process with PID 198 reaped.
[04:22:25/31] Received SIGCHLD, 0 active tasks left.

**其他**
任何有助于 bug 修复的信息。

**Comment by HenryQW** [comment]
rsshub 是 80/443 端口吗？不是的话有没有在 ALLOW_PORTS 添加对应的端口？

**Comment by HawkQ** [comment]
> rsshub 是 80/443 端口吗？不是的话有没有在 ALLOW_PORTS 添加对应的端口？

之前确实不是，已经阅读其他issue修改完毕啦，谢谢您！
