### ISSUE TITLE
[BUG] TTRSS does not start from version latest-2022-12-23

### ISSUE THREAD

**Issue by stevenliatti** [HenryQW/Awesome-TTRSS#431]
**Describe the bug**
I have been using this Docker image for years without any problems, thank you very much for the work :+1: But since the image update two weeks ago, TTRSS does not start when the Docker image is newer than [nightly-2022-11-12](https://hub.docker.com/layers/wangqiru/ttrss/nightly-2022-11-12/images/sha256-d940b8ed2a0e76be5fa68a959b1051819463cd72fe1d120ebb95e91ef1103252) and when I open my browser on my TTRSS URL, there is a blank page and I see error codes 500 on my reverse-proxy logs.

**Have you googled?**
Yes, but I can't find anything related.

**Deployment method**
Docker-compose with the main image `wangqiru/ttrss` and `postgres:13-alpine`

**Deployment environment**
 - OS: Debian 10
 - Browser: Firefox

**To Reproduce**
Make a `docker-compose pull && docker-compose up -d`

**Expected behavior**
I would like ttrss to start

**Error logs**
I compared the startup logs between the different versions of the images, there are no major differences, there are no explicit error logs at least.

**Comment by TonyRL** [comment]
I guess it would be better for troubleshooting if you can provide the logs

docker startup logs
```sh
docker logs ttrss
```

web server logs
```sh
docker exec ttrss cat /var/log/nginx/error.log
```

**Comment by stevenliatti** [comment]
Thanks for response.

Here is the the docker DB and startup logs :
```
ttrss-db_1               | 
ttrss-db_1               | PostgreSQL Database directory appears to contain a database; Skipping initialization
ttrss-db_1               | 
ttrss-db_1               | 2023-01-08 09:55:56.385 UTC [1] LOG:  starting PostgreSQL 13.9 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
ttrss-db_1               | 2023-01-08 09:55:56.386 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
ttrss-db_1               | 2023-01-08 09:55:56.386 UTC [1] LOG:  listening on IPv6 address "::", port 5432
ttrss-db_1               | 2023-01-08 09:55:56.400 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
ttrss-db_1               | 2023-01-08 09:55:56.413 UTC [22] LOG:  database system was shut down at 2023-01-08 09:55:32 UTC
ttrss-db_1               | 2023-01-08 09:55:56.434 UTC [1] LOG:  database system is ready to accept connections
ttrss-app_1              | [09:55:57/24] Lock: update.lock
ttrss-app_1              | [09:55:57/24] Database schema is already at latest version.
ttrss-app_1              | [09:55:57/30] Spawn interval: 120 sec
ttrss-app_1              | [09:55:57/30] Installing shutdown handlers
ttrss-app_1              | [09:55:57/30] Spawned child process with PID 34 for task 0.
ttrss-app_1              | [09:55:57/30] Spawned child process with PID 36 for task 1.
ttrss-app_1              | [09:55:57/35] Using task id 0
ttrss-app_1              | [09:55:57/37] Using task id 1
ttrss-app_1              | [09:55:57/35] Lock: update_daemon-34.lock
ttrss-app_1              | [09:55:57/37] Lock: update_daemon-36.lock
ttrss-app_1              | [09:55:57/35] Waiting before update (0)...
ttrss-app_1              | [09:55:57/37] Waiting before update (5)...
ttrss-app_1              | [09:55:57/35] Scheduled 1 feeds to update...
ttrss-app_1              | [09:55:57/35] Base feed: https://www.example1.com
ttrss-app_1              | [09:55:57/35] => example1.com (ID: 12, U: steven [2]), last updated: 2023-01-08 09:25:55
ttrss-app_1              | [09:55:58/42] Lock: update_daemon-feed-12.lock
ttrss-app_1              | [09:56:01/35] <= 3.3188 (sec) exit code: 0
ttrss-app_1              | [09:56:01/35] Processed 1 feeds in 3.3390 (sec), 3.3390 (sec/feed avg)
ttrss-app_1              | [09:56:01/35] Running housekeeping tasks for user 2...
ttrss-app_1              | [09:56:01/35] Sending digests, batch of max 15 users, headline limit = 1000
ttrss-app_1              | [09:56:01/35] All done.
ttrss-app_1              | [09:56:01/35] Expired cache/export: removed 0 files.
ttrss-app_1              | [09:56:01/35] Expired cache/feeds: removed 0 files.
ttrss-app_1              | [09:56:01/35] Expired cache/images: removed 0 files.
ttrss-app_1              | [09:56:01/35] Expired cache/upload: removed 0 files.
ttrss-app_1              | [09:56:01/35] Removed 0 old lock files.
ttrss-app_1              | [09:56:01/35] Removing old error log entries...
ttrss-app_1              | [09:56:01/35] Purged 0 orphaned posts.
ttrss-app_1              | [09:56:02/30] Child process with PID 34 reaped.
ttrss-app_1              | [09:56:02/30] Received SIGCHLD, 1 active tasks left.
ttrss-app_1              | [09:56:02/37] Scheduled 0 feeds to update...
ttrss-app_1              | [09:56:02/37] Sending digests, batch of max 15 users, headline limit = 1000
ttrss-app_1              | [09:56:02/37] All done.
ttrss-app_1              | [09:56:03/30] Child process with PID 36 reaped.
ttrss-app_1              | [09:56:03/30] Received SIGCHLD, 0 active tasks left.
ttrss-app_1              | [09:56:57/30] 0 active tasks, next spawn at 60 sec.
ttrss-app_1              | [09:57:57/30] 0 active tasks, next spawn at 0 sec.
ttrss-app_1              | [09:57:58/30] Spawned child process with PID 66 for task 0.
ttrss-app_1              | [09:57:58/30] Spawned child process with PID 68 for task 1.
ttrss-app_1              | [09:57:59/69] Using task id 1
ttrss-app_1              | [09:57:59/67] Using task id 0
ttrss-app_1              | [09:57:59/69] Lock: update_daemon-68.lock
ttrss-app_1              | [09:57:59/67] Lock: update_daemon-66.lock
ttrss-app_1              | [09:57:59/69] Waiting before update (5)...
ttrss-app_1              | [09:57:59/67] Waiting before update (0)...
ttrss-app_1              | [09:57:59/67] Scheduled 0 feeds to update...
ttrss-app_1              | [09:57:59/67] Sending digests, batch of max 15 users, headline limit = 1000
ttrss-app_1              | [09:57:59/67] All done.
ttrss-app_1              | [09:57:59/67] Expired cache/export: removed 0 files.
ttrss-app_1              | [09:57:59/67] Expired cache/feeds: removed 0 files.
ttrss-app_1              | [09:57:59/67] Expired cache/images: removed 0 files.
ttrss-app_1              | [09:57:59/67] Expired cache/upload: removed 0 files.
ttrss-app_1              | [09:57:59/67] Removed 0 old lock files.
ttrss-app_1              | [09:57:59/67] Removing old error log entries...
ttrss-app_1              | [09:57:59/67] Purged 0 orphaned posts.
ttrss-app_1              | [09:58:00/30] Child process with PID 66 reaped.
ttrss-app_1              | [09:58:00/30] Received SIGCHLD, 1 active tasks left.
ttrss-app_1              | [09:58:04/69] Scheduled 0 feeds to update...
ttrss-app_1              | [09:58:04/69] Sending digests, batch of max 15 users, headline limit = 1000
ttrss-app_1              | [09:58:04/69] All done.
ttrss-app_1              | [09:58:05/30] Child process with PID 68 reaped.
ttrss-app_1              | [09:58:05/30] Received SIGCHLD, 0 active tasks left.
ttrss-app_1              | [09:58:58/30] 0 active tasks, next spawn at 60 sec.
ttrss-app_1              | [09:59:58/30] 0 active tasks, next spawn at 0 sec.
ttrss-app_1              | [09:59:59/30] Spawned child process with PID 109 for task 0.
ttrss-app_1              | [09:59:59/30] Spawned child process with PID 111 for task 1.
ttrss-app_1              | [09:59:59/110] Using task id 0
ttrss-app_1              | [09:59:59/112] Using task id 1
ttrss-app_1              | [09:59:59/110] Lock: update_daemon-109.lock
ttrss-app_1              | [09:59:59/112] Lock: update_daemon-111.lock
ttrss-app_1              | [09:59:59/110] Waiting before update (0)...
ttrss-app_1              | [09:59:59/112] Waiting before update (5)...
ttrss-app_1              | [09:59:59/110] Scheduled 1 feeds to update...
ttrss-app_1              | [09:59:59/110] Base feed: http://www.example2.com
ttrss-app_1              | [09:59:59/110] => example2.com (ID: 13, U: steven [2]), last updated: 2023-01-08 09:29:56
ttrss-app_1              | [09:59:59/115] Lock: update_daemon-feed-13.lock
ttrss-app_1              | [10:00:02/110] <= 2.7145 (sec) exit code: 0
ttrss-app_1              | [10:00:02/110] Processed 1 feeds in 2.7340 (sec), 2.7340 (sec/feed avg)
ttrss-app_1              | [10:00:02/110] Running housekeeping tasks for user 2...
ttrss-app_1              | [10:00:02/110] Sending digests, batch of max 15 users, headline limit = 1000
ttrss-app_1              | [10:00:02/110] All done.
ttrss-app_1              | [10:00:02/110] Expired cache/export: removed 0 files.
ttrss-app_1              | [10:00:02/110] Expired cache/feeds: removed 0 files.
ttrss-app_1              | [10:00:02/110] Expired cache/images: removed 0 files.
ttrss-app_1              | [10:00:02/110] Expired cache/upload: removed 0 files.
ttrss-app_1              | [10:00:02/110] Removed 0 old lock files.
ttrss-app_1              | [10:00:02/110] Removing old error log entries...
ttrss-app_1              | [10:00:02/110] Purged 0 orphaned posts.
ttrss-app_1              | [10:00:03/30] Child process with PID 109 reaped.
ttrss-app_1              | [10:00:03/30] Received SIGCHLD, 1 active tasks left.
ttrss-app_1              | [10:00:04/112] Scheduled 1 feeds to update...
ttrss-app_1              | [10:00:04/112] Base feed: https://www.example3.com
ttrss-app_1              | [10:00:04/112] => example3.com News (ID: 31, U: steven [2]), last updated: 2023-01-08 09:30:00
ttrss-app_1              | [10:00:04/122] Lock: update_daemon-feed-31.lock
ttrss-app_1              | [10:00:09/112] <= 4.7370 (sec) exit code: 0
ttrss-app_1              | [10:00:09/112] Processed 1 feeds in 4.7552 (sec), 4.7552 (sec/feed avg)
ttrss-app_1              | [10:00:09/112] Running housekeeping tasks for user 2...
ttrss-app_1              | [10:00:09/112] Sending digests, batch of max 15 users, headline limit = 1000
ttrss-app_1              | [10:00:09/112] All done.
ttrss-app_1              | [10:00:10/30] Child process with PID 111 reaped.
ttrss-app_1              | [10:00:10/30] Received SIGCHLD, 0 active tasks left.
```


And here the web server logs :
```
2023/01/08 10:10:06 [error] 32#32: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  During inheritance of ArrayAccess: Uncaught Error: Class "ORM" not found in /var/www/classes/logger/sql.php:9
Stack trace:
#0 /var/www/classes/logger.php(59): Logger_SQL->__construct()
#1 /var/www/classes/logger.php(77): Logger->__construct()
#2 /var/www/classes/logger.php(29): Logger::get_instance()
#3 /var/www/include/errorhandler.php(57): Logger::log_error()
#4 /var/www/vendor/j4mie/idiorm/idiorm.php(115): ttrss_error_handler()
#5 /var/www/vendor/composer/ClassLoader.php(478): include('...')
#6 /var/www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#7 /var/www/classes/db.php(13): Composer\Autoload\ClassLoader->loadClass()
#8 /var/www/classes/db.php(76): Db->__construct()
#9 /var/www/classes/db/migrations.php(16): Db::pdo()
#10 /var/www/classes/config.php(339): Db_Migrations->__construct()
#11 /var/www/classes/config.php(334): Config->_get_migrations()
#12 /var/www/classes/config.php(351): Config::get_migrations()
#13 /var/www/include/sessio...PHP message: PHP Fatal error:  Uncaught Error: Class "ORM" not found in /var/www/classes/logger/sql.php:9
Stack trace:
#0 /var/www/classes/logger.php(59): Logger_SQL->__construct()
#1 /var/www/classes/logger.php(77): Logger->__construct()
#2 /var/www/classes/logger.php(29): Logger::get_instance()
#3 /var/www/include/errorhandler.php(78): Logger::log_error()
#4 [internal function]: ttrss_fatal_handler()
#5 {main}
  thrown in /var/www/classes/logger/sql.php on line 9" while reading response header from upstream, client: 172.18.0.6, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "myttrss.example.com"
```

**Comment by dimon222** [comment]
Unable to replicate. I've just launched from scratch on latest nightly (2 months old) - it works fine.
